//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarIsYourHome
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllManualCar
    {
        public string Manufacture { get; set; }
        public string Model { get; set; }
        public decimal Daily_Cost { get; set; }
        public decimal Daily_Delay_Cost { get; set; }
        public int Year { get; set; }
        public string Transmission { get; set; }
    }
}
