//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarIsYourHome
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars_List
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars_List()
        {
            this.Rented_Cars = new HashSet<Rented_Car>();
        }
    
        public int Car_ID { get; set; }
        public int Type_ID { get; set; }
        public string License_Plate { get; set; }
        public decimal Mileage { get; set; }
        public string Status { get; set; }
        public string Available { get; set; }
        public Nullable<int> Branch_ID { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Cars_List Cars_List1 { get; set; }
        public virtual Cars_List Cars_List2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rented_Car> Rented_Cars { get; set; }
        public virtual Cars_Type Cars_Types { get; set; }
    }
}
