//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarIsYourHome
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllCarRented
    {
        public int Rent_ID { get; set; }
        public int Car_ID { get; set; }
        public string License_Plate { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime Return { get; set; }
        public Nullable<System.DateTime> Actual_Return { get; set; }
        public Nullable<int> User_ID { get; set; }
    }
}
